CREATE TABLE IF NOT EXISTS raw_stage_grants.pres_grants (
	"name" varchar(2000) NULL,
	contest varchar(50) NULL,
	"year" int8 NULL,
	direction varchar(250) NULL,
	date_req date NULL,
	region varchar(50) NULL,
	org varchar(500) NULL,
	inn varchar(20) NULL,
	ogrn varchar(20) NULL,
	implem_start date NULL,
	implem_end date NULL,
	winner bool NULL,
	rate numeric(5, 2) NULL,
	money_req_grant numeric(15, 2) NULL,
	cofunding numeric(15, 2) NULL,
	total_money numeric(15, 2) NULL,
	description varchar(5000) NULL,
	goal varchar(3000) NULL,
	tasks varchar(8000) NULL,
	soc_signif varchar(5000) NULL,
	pj_geo varchar(2000) NULL,
	target_groups varchar(8000) NULL,
	address varchar(250) NULL,
	web_site varchar(1000) NULL,
	req_num varchar(50) NULL,
	link varchar(250) NULL,
	okato varchar(8) NULL,
	oktmo varchar(8) NULL,
	"level" varchar(50) NULL,
	record_source varchar(50) NOT NULL,
	load_datetime timestamp NOT NULL
)